### PR TITLE
update qq.deb to 3.2.1-17260 and disable wayland

### PR DESCRIPTION
**Pull request by asuka909**

### CODE REVIEW

**Comment by asuka909** [comment]
bot, build

**Comment by asuka909** [comment]
bot, build

**Comment by chenzhiwei** [comment]
ok, I will verify this pr later, if everything goes well, I will merge it.

**Comment by asuka909** [comment]
> ok, I will verify this pr later, if everything goes well, I will merge it.

I'm sorry I forgot to update the appdata file. I'll push a commit right now

**Comment by asuka909** [comment]
bot, build

**Comment by asuka909** [comment]
bot, build

**Comment by chenzhiwei** [comment]
@catsout could you please take a look?

**Comment by chenzhiwei** [comment]
btw, could you enable the x-checker(https://github.com/flathub/com.qq.QQ/pull/26)?

**Comment by catsout** [comment]
> @catsout could you please take a look?

I think it's ok.

**Comment by chenzhiwei** [comment]
I think we need to re-enable Wayland sometime later.

**Pull request merged**
