### PR TITLE
update qq.deb to 3.2.0-16605

### PR DESCRIPTION
**Pull request by Rsplwe**

### CODE REVIEW

**Comment by Rsplwe** [comment]
Build test failure: the upstream server failed to download the deb package.

**Comment by chenzhiwei** [comment]
bot, build

**Comment by AzureZeng** [comment]
bot, build

**Comment by AzureZeng** [comment]
bot, build

**Comment by chenzhiwei** [comment]
@Rsplwe ptal

**Comment by Rsplwe** [comment]
bot, build

**Comment by Rsplwe** [comment]
@chenzhiwei build success

**Pull request merged**
