### PR TITLE
bump org.electronjs.Electron2.BaseApp to 23.08

### PR DESCRIPTION
**Pull request by asuka909**
um.. I just want to do this. No significant change.

### CODE REVIEW

**Comment by asuka909** [comment]
bot, build

**Comment by chenzhiwei** [comment]
> um.. I just want to do this. No significant change.

I like this idea

**Comment by asuka909** [comment]
@chenzhiwei  Maybe we shouldn't accept updates that haven't been posted to the download page yet. It confuses x-data-checker somehow. Or we can look into how Arch people are getting newer update than the download page.

**Comment by chenzhiwei** [comment]
sure, will not merge such pr in future.

**Pull request closed without merging**
