### PR TITLE
Fix file receive issue

### PR DESCRIPTION
**Pull request by asuka909**
maybe we should create a new dir to make it look clean... "etc" might be a bad idea but i just open pr for test now.

### CODE REVIEW

**Comment by asuka909** [comment]
```fatal: unable to access 'https://github.com/flathub/com.qq.QQ/': gnutls_handshake() failed: The TLS connection was non-properly terminated.```

**Comment by asuka909** [comment]
bot,build

**Comment by asuka909** [comment]
bot, build

**Comment by chenzhiwei** [comment]
bot build

**Comment by chenzhiwei** [comment]
bot, build

**Comment by chenzhiwei** [comment]
let's create a patch dir and add comments in the patch file to state why introducing this patch.

**Comment by asuka909** [comment]
> let's create a patch dir and add comments in the patch file to state why introducing this patch.

Okay I'll do this tomorrow. Also I'll check if we can replace the read and write method with sendfile() for better performance.

**Comment by asuka909** [comment]
bot, build

**Comment by asuka909** [comment]
@chenzhiwei don't merge. has serious bug. i will look into it.

**Comment by asuka909** [comment]
bot, build

**Comment by asuka909** [comment]
bot, build

**Comment by asuka909** [comment]
bot, build

**Comment by asuka909** [comment]
bot, build

**Comment by asuka909** [comment]
bot, build

**Comment by chenzhiwei** [comment]
腾讯的QQ下载链接是不是没给海外弄CDN，咋总是超时呢。

**Comment by chenzhiwei** [comment]
bot, build

**Comment by asuka909** [comment]
@chenzhiwei 这个要多测试一下毕竟Hook了glibc，我运行了两三个小时没什么问题。

**Comment by asuka909** [comment]
bot, build

**Comment by asuka909** [comment]
@chenzhiwei 这个 buildbot 太折磨了。代码没问题了，我也本地测试了，再跑一下构建，成功就可以merge了。

**Comment by asuka909** [comment]
bot, build

**Pull request merged**
